name:                haskell-learn
version:             0.1.0.0
github:              "rolandtritsch/haskell-learn"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2018 Roland Tritsch"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/rolandtritsch/haskell-learn#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-learn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-learn

tests:
  haskell-learn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-learn
    - hspec
